import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Navibar from "@/components/Navibar";
import QueryClientProvider from "@/components/QueryClientProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const publishableKey = process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY;
  return publishableKey ? (
    <ClerkProvider publishableKey={publishableKey}>
      <QueryClientProvider>
        <html lang="en">
          <body className="antialiased flex flex-row">
            <div className="w-1/5 h-screen bg-gray-50">
              <Navibar />
            </div>
            <div className="w-4/5 h-screen bg-white overflow-auto">
              {children}
            </div>
          </body>
        </html>
      </QueryClientProvider>
    </ClerkProvider>
  ) : (
    <QueryClientProvider>
      <html lang="en">
        <body className="antialiased flex flex-row">
          <div className="w-1/5 h-screen bg-gray-50">
            <Navibar />
          </div>
          <div className="w-4/5 h-screen bg-white overflow-auto">
            {children}
          </div>
        </body>
      </html>
    </QueryClientProvider>
  );
}
